# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(282, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.page_3)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.btn_Sendfile = QtWidgets.QPushButton(self.frame_5)
        self.btn_Sendfile.setStyleSheet("")
        self.btn_Sendfile.setObjectName("btn_Sendfile")
        self.gridLayout_15.addWidget(self.btn_Sendfile, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_15.addItem(spacerItem1, 2, 0, 1, 1)
        self.btn_Game = QtWidgets.QPushButton(self.frame_5)
        self.btn_Game.setStyleSheet("")
        self.btn_Game.setObjectName("btn_Game")
        self.gridLayout_15.addWidget(self.btn_Game, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_15.addItem(spacerItem2, 8, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_15.addItem(spacerItem3, 6, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_15.addItem(spacerItem4, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_15.addItem(spacerItem5, 10, 0, 1, 1)
        self.btn_Connect = QtWidgets.QPushButton(self.frame_5)
        self.btn_Connect.setStyleSheet("")
        self.btn_Connect.setObjectName("btn_Connect")
        self.gridLayout_15.addWidget(self.btn_Connect, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_15.addItem(spacerItem6, 0, 0, 1, 1)
        self.btn_Streaming = QtWidgets.QPushButton(self.frame_5)
        self.btn_Streaming.setStyleSheet("")
        self.btn_Streaming.setObjectName("btn_Streaming")
        self.gridLayout_15.addWidget(self.btn_Streaming, 5, 0, 1, 1)
        self.btn_Recievefile = QtWidgets.QPushButton(self.frame_5)
        self.btn_Recievefile.setStyleSheet("")
        self.btn_Recievefile.setObjectName("btn_Recievefile")
        self.gridLayout_15.addWidget(self.btn_Recievefile, 9, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_5, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.ln_IP = QtWidgets.QLineEdit(self.frame_4)
        self.ln_IP.setObjectName("ln_IP")
        self.horizontalLayout_5.addWidget(self.ln_IP)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.ln_name = QtWidgets.QLineEdit(self.frame_4)
        self.ln_name.setObjectName("ln_name")
        self.horizontalLayout_4.addWidget(self.ln_name)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.gridLayout_10.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_10.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_2 = QtWidgets.QFrame(self.page_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lbl_1 = QtWidgets.QLabel(self.frame_3)
        self.lbl_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_1.setText("")
        self.lbl_1.setObjectName("lbl_1")
        self.gridLayout_17.addWidget(self.lbl_1, 0, 0, 1, 1)
        self.lbl_2 = QtWidgets.QLabel(self.frame_3)
        self.lbl_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_2.setText("")
        self.lbl_2.setObjectName("lbl_2")
        self.gridLayout_17.addWidget(self.lbl_2, 0, 1, 1, 1)
        self.lbl_3 = QtWidgets.QLabel(self.frame_3)
        self.lbl_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_3.setText("")
        self.lbl_3.setObjectName("lbl_3")
        self.gridLayout_17.addWidget(self.lbl_3, 0, 2, 1, 1)
        self.lbl_4 = QtWidgets.QLabel(self.frame_3)
        self.lbl_4.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_4.setText("")
        self.lbl_4.setObjectName("lbl_4")
        self.gridLayout_17.addWidget(self.lbl_4, 1, 0, 1, 1)
        self.lbl_9 = QtWidgets.QLabel(self.frame_3)
        self.lbl_9.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_9.setText("")
        self.lbl_9.setObjectName("lbl_9")
        self.gridLayout_17.addWidget(self.lbl_9, 2, 2, 1, 1)
        self.lbl_7 = QtWidgets.QLabel(self.frame_3)
        self.lbl_7.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_7.setText("")
        self.lbl_7.setObjectName("lbl_7")
        self.gridLayout_17.addWidget(self.lbl_7, 2, 0, 1, 1)
        self.lbl_5 = QtWidgets.QLabel(self.frame_3)
        self.lbl_5.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_5.setText("")
        self.lbl_5.setObjectName("lbl_5")
        self.gridLayout_17.addWidget(self.lbl_5, 1, 1, 1, 1)
        self.lbl_8 = QtWidgets.QLabel(self.frame_3)
        self.lbl_8.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_8.setText("")
        self.lbl_8.setObjectName("lbl_8")
        self.gridLayout_17.addWidget(self.lbl_8, 2, 1, 1, 1)
        self.lbl_6 = QtWidgets.QLabel(self.frame_3)
        self.lbl_6.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_6.setText("")
        self.lbl_6.setObjectName("lbl_6")
        self.gridLayout_17.addWidget(self.lbl_6, 1, 2, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_3, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem11, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem12, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_16, 2, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ln_name2 = QtWidgets.QLineEdit(self.frame_2)
        self.ln_name2.setReadOnly(True)
        self.ln_name2.setObjectName("ln_name2")
        self.verticalLayout_5.addWidget(self.ln_name2)
        self.btn_Gamestart = QtWidgets.QPushButton(self.frame_2)
        self.btn_Gamestart.setObjectName("btn_Gamestart")
        self.verticalLayout_5.addWidget(self.btn_Gamestart)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.gridLayout_14.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_9.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_9.addWidget(self.pushButton_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        self.gridLayout_14.addLayout(self.verticalLayout_6, 3, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem13)
        self.btn_Startstreaming = QtWidgets.QPushButton(self.frame)
        self.btn_Startstreaming.setObjectName("btn_Startstreaming")
        self.verticalLayout.addWidget(self.btn_Startstreaming)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem14)
        self.btn_Endstreaming = QtWidgets.QPushButton(self.frame)
        self.btn_Endstreaming.setObjectName("btn_Endstreaming")
        self.verticalLayout.addWidget(self.btn_Endstreaming)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem15)
        self.btn_Back = QtWidgets.QPushButton(self.frame)
        self.btn_Back.setObjectName("btn_Back")
        self.verticalLayout.addWidget(self.btn_Back)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem16)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem17, 0, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem18, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(2)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_Startchat = QtWidgets.QPushButton(self.frame_6)
        self.btn_Startchat.setObjectName("btn_Startchat")
        self.gridLayout_3.addWidget(self.btn_Startchat, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.frame_6)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 2, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem19, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.btn_Send = QtWidgets.QPushButton(self.frame_6)
        self.btn_Send.setObjectName("btn_Send")
        self.horizontalLayout_6.addWidget(self.btn_Send)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem20 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem20)
        self.btn_Backfromchat = QtWidgets.QPushButton(self.frame_6)
        self.btn_Backfromchat.setObjectName("btn_Backfromchat")
        self.verticalLayout_2.addWidget(self.btn_Backfromchat)
        self.gridLayout_20.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_20, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Sendfile.setText(_translate("MainWindow", "Send File"))
        self.btn_Game.setText(_translate("MainWindow", "Game"))
        self.btn_Connect.setText(_translate("MainWindow", "Chat"))
        self.btn_Streaming.setText(_translate("MainWindow", "Streaming"))
        self.btn_Recievefile.setText(_translate("MainWindow", "Recieve File"))
        self.label.setText(_translate("MainWindow", " IP:                       "))
        self.label_2.setText(_translate("MainWindow", "Enter Your Name:"))
        self.btn_Gamestart.setText(_translate("MainWindow", "Game Start"))
        self.pushButton.setText(_translate("MainWindow", "End Game"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))
        self.btn_Startstreaming.setText(_translate("MainWindow", "Start Streaming"))
        self.btn_Endstreaming.setText(_translate("MainWindow", "Recieve Streaming"))
        self.btn_Back.setText(_translate("MainWindow", "Back"))
        self.btn_Startchat.setText(_translate("MainWindow", "Strat"))
        self.btn_Send.setText(_translate("MainWindow", "Send"))
        self.btn_Backfromchat.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

