# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(406, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lbl_IP = QtWidgets.QLabel(self.page)
        self.lbl_IP.setObjectName("lbl_IP")
        self.horizontalLayout_10.addWidget(self.lbl_IP)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ln_IP = QtWidgets.QLineEdit(self.page)
        self.ln_IP.setReadOnly(True)
        self.ln_IP.setObjectName("ln_IP")
        self.horizontalLayout_12.addWidget(self.ln_IP)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ln_name = QtWidgets.QLineEdit(self.page)
        self.ln_name.setEnabled(True)
        self.ln_name.setAccessibleName("")
        self.ln_name.setAutoFillBackground(False)
        self.ln_name.setInputMask("")
        self.ln_name.setText("")
        self.ln_name.setObjectName("ln_name")
        self.horizontalLayout_14.addWidget(self.ln_name)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem4)
        self.btn_Connect = QtWidgets.QPushButton(self.page)
        self.btn_Connect.setObjectName("btn_Connect")
        self.verticalLayout_2.addWidget(self.btn_Connect)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem5)
        self.btn_Game = QtWidgets.QPushButton(self.page)
        self.btn_Game.setObjectName("btn_Game")
        self.verticalLayout_2.addWidget(self.btn_Game)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem6)
        self.btn_Streaming = QtWidgets.QPushButton(self.page)
        self.btn_Streaming.setObjectName("btn_Streaming")
        self.verticalLayout_2.addWidget(self.btn_Streaming)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.btn_Sendfile = QtWidgets.QPushButton(self.page)
        self.btn_Sendfile.setObjectName("btn_Sendfile")
        self.verticalLayout_2.addWidget(self.btn_Sendfile)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem8)
        self.btn_Recievefile = QtWidgets.QPushButton(self.page)
        self.btn_Recievefile.setObjectName("btn_Recievefile")
        self.verticalLayout_2.addWidget(self.btn_Recievefile)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem9)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lbl_5 = QtWidgets.QLabel(self.page_3)
        self.lbl_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_5.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_5.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_5.setText("")
        self.lbl_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_5.setObjectName("lbl_5")
        self.gridLayout_9.addWidget(self.lbl_5, 1, 2, 1, 1)
        self.lbl_1 = QtWidgets.QLabel(self.page_3)
        self.lbl_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_1.setMouseTracking(True)
        self.lbl_1.setTabletTracking(False)
        self.lbl_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_1.setAutoFillBackground(True)
        self.lbl_1.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_1.setText("")
        self.lbl_1.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_1.setScaledContents(True)
        self.lbl_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_1.setObjectName("lbl_1")
        self.gridLayout_9.addWidget(self.lbl_1, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 1, 4, 1, 1)
        self.lbl_9 = QtWidgets.QLabel(self.page_3)
        self.lbl_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_9.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_9.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_9.setText("")
        self.lbl_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_9.setObjectName("lbl_9")
        self.gridLayout_9.addWidget(self.lbl_9, 2, 3, 1, 1)
        self.lbl_8 = QtWidgets.QLabel(self.page_3)
        self.lbl_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_8.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_8.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_8.setText("")
        self.lbl_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_8.setObjectName("lbl_8")
        self.gridLayout_9.addWidget(self.lbl_8, 2, 2, 1, 1)
        self.lbl_4 = QtWidgets.QLabel(self.page_3)
        self.lbl_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_4.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_4.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_4.setText("")
        self.lbl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_4.setObjectName("lbl_4")
        self.gridLayout_9.addWidget(self.lbl_4, 1, 1, 1, 1)
        self.lbl_3 = QtWidgets.QLabel(self.page_3)
        self.lbl_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_3.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_3.setText("")
        self.lbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_3.setObjectName("lbl_3")
        self.gridLayout_9.addWidget(self.lbl_3, 0, 3, 1, 1)
        self.lbl_6 = QtWidgets.QLabel(self.page_3)
        self.lbl_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_6.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_6.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_6.setText("")
        self.lbl_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_6.setObjectName("lbl_6")
        self.gridLayout_9.addWidget(self.lbl_6, 1, 3, 1, 1)
        self.lbl_7 = QtWidgets.QLabel(self.page_3)
        self.lbl_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_7.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_7.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_7.setText("")
        self.lbl_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_7.setObjectName("lbl_7")
        self.gridLayout_9.addWidget(self.lbl_7, 2, 1, 1, 1)
        self.lbl_2 = QtWidgets.QLabel(self.page_3)
        self.lbl_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_2.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"text-align: center;")
        self.lbl_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_2.setText("")
        self.lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_2.setObjectName("lbl_2")
        self.gridLayout_9.addWidget(self.lbl_2, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ln_name2 = QtWidgets.QLineEdit(self.page_3)
        self.ln_name2.setReadOnly(True)
        self.ln_name2.setObjectName("ln_name2")
        self.verticalLayout_3.addWidget(self.ln_name2)
        self.btn_Gamestart = QtWidgets.QPushButton(self.page_3)
        self.btn_Gamestart.setObjectName("btn_Gamestart")
        self.verticalLayout_3.addWidget(self.btn_Gamestart)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.gridLayout_12.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem14, 0, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem15, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btn_Startstreaming = QtWidgets.QPushButton(self.page_4)
        self.btn_Startstreaming.setObjectName("btn_Startstreaming")
        self.gridLayout_8.addWidget(self.btn_Startstreaming, 0, 0, 1, 1)
        self.btn_Back = QtWidgets.QPushButton(self.page_4)
        self.btn_Back.setObjectName("btn_Back")
        self.gridLayout_8.addWidget(self.btn_Back, 2, 0, 1, 1)
        self.btn_Endstreaming = QtWidgets.QPushButton(self.page_4)
        self.btn_Endstreaming.setObjectName("btn_Endstreaming")
        self.gridLayout_8.addWidget(self.btn_Endstreaming, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 406, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_IP.setText(_translate("MainWindow", "IP "))
        self.label_3.setText(_translate("MainWindow", "Enter Player Name"))
        self.btn_Connect.setText(_translate("MainWindow", "Connect"))
        self.btn_Game.setText(_translate("MainWindow", "Game"))
        self.btn_Streaming.setText(_translate("MainWindow", " Streaming"))
        self.btn_Sendfile.setText(_translate("MainWindow", "Send File"))
        self.btn_Recievefile.setText(_translate("MainWindow", "Recieve File"))
        self.btn_Gamestart.setText(_translate("MainWindow", "Start Game"))
        self.pushButton.setText(_translate("MainWindow", "End Game"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))
        self.btn_Startstreaming.setText(_translate("MainWindow", "Start Streaming"))
        self.btn_Back.setText(_translate("MainWindow", "Back"))
        self.btn_Endstreaming.setText(_translate("MainWindow", "End Streaming"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

